name: Add pull request or issue to project
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
      - reopened
      - transferred

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  add-to-project:
    name: Add pull request or issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/NatLabRockies/projects/38
          github-token: ${{ secrets.GHB_TOKEN }}
